### ISSUE TITLE
Публичная часть класса

### ISSUE THREAD

**Issue by avasyukov** [KonstantinKurochka/1zadanie#2]
Вы не стали реализовывать интерфейс Container. Ну ок. Но по сути класс должен соответствовать заданию.

Прототип класса сейчас вот такой:
https://github.com/KonstantinKurochka/1zadanie/blob/3eac62b00af81224154bd1f82afd664a23e41c7c/binary_tree.cpp#L7-L28

В публичной части должны остаться:
```c++
    void insert(int value);
    bool exists(int value);
    void remove(int value);
    void print();
```
и всё. Остальные методы - под капот, в protected/private. Переменные - тоже. В публичной части не должно оставаться параметра ```BinTreeEl* root``` - его тоже под капот. И возвращаемые указатели - тоже.

**Comment by KonstantinKurochka** [comment]
Исправлено, все функции переписаны через this. В публичной части 4 функции.

**Comment by avasyukov** [comment]
У insert осталось лишнее возвращаемое значение.

**Comment by avasyukov** [comment]
Сделано
