### ISSUE TITLE
Логика работы пустого дерева

### ISSUE THREAD

**Issue by avasyukov** [KonstantinKurochka/1zadanie#3]
Если сейчас вызвать:
```c++
int main()
{
    BinTreeEl* c = new BinTreeEl();
    cout << "Value 0 exists: " << boolalpha << c->exists(c, 0) << endl;
    delete c;
    return 0;
}
```
то внезапно случается:
```
Value 0 exists: true
```

Но дерево пустое, значений в нём ещё нет никаких. Это поведение нужно починить.

**Comment by KonstantinKurochka** [comment]
Новый вариант дерева на данный main выводит false.

**Comment by avasyukov** [comment]
Возможно, новый вариант не был залит.

**Comment by avasyukov** [comment]
Ок, разобрались вживую. Это наводки от более глубокой проблемы, на неё будет отдельный тикет.
